# Generated by Django 6.0.1 on 2026-01-13 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsubscription',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopsubscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
